# Generated by Django 5.1.6 on 2025-02-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'usd'), ('eur', 'eur'), ('rub', 'rub')], default='usd', max_length=3, verbose_name='Валюта'),
        ),
    ]
