# Generated by Django 5.1.6 on 2025-03-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_order_discount_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.ManyToManyField(blank=True, to='payment.discount', verbose_name='Скидка'),
        ),
    ]
